# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaehlimrJtCqvK6HvLjQbK4i9K5zCHQb
"""

# Retail Sales Analysis Project
# -----------------------------

# Step 1: Import libraries
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Create sample dataset
data = {
    "Shop": ["Shop1","Shop2","Shop3","Shop4","Shop5"] * 3,
    "Product": ["Milk","Bread","Rice"] * 5,
    "Price": [500, 600, 700, 550, 450, 800, 650, 720, 480, 620, 700, 750, 570, 660, 520],
    "Quantity": [10, 7, 5, 9, 6, 12, 8, 11, 5, 7, 9, 10, 6, 8, 7]
}

df = pd.DataFrame(data)

# Step 3: Calculate total sales
df["Total"] = df["Price"] * df["Quantity"]

# Step 4: Summary per shop
shop_sales = df.groupby("Shop")["Total"].sum()
print("Total Sales per Shop:\n", shop_sales)

# Step 5: Visualization - Sales per Shop
shop_sales.plot(kind="bar", figsize=(7,4), title="Sales per Shop", color="skyblue")
plt.ylabel("Total Sales")
plt.show()

# Step 6: Summary per product
product_sales = df.groupby("Product")["Total"].sum()
print("\nTotal Sales per Product:\n", product_sales)

# Step 7: Visualization - Sales per Product
product_sales.plot(kind="pie", autopct="%1.1f%%", figsize=(5,5), title="Sales Distribution by Product")
plt.ylabel("")  # remove ylabel for clean pie chart
plt.show()