# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NaehlimrJtCqvK6HvLjQbK4i9K5zCHQb
"""

# Titanic Exploratory Data Analysis
# ---------------------------------

# Step 1: Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Step 2: Load dataset (Titanic dataset from seaborn)
df = sns.load_dataset("titanic")

# Step 3: Preview data
print("Dataset shape:", df.shape)
print(df.head())

# Step 4: Missing values check
print("\nMissing values:\n", df.isnull().sum())

# Step 5: Survival rate overall
survival_rate = df['survived'].mean() * 100
print(f"\nOverall Survival Rate: {survival_rate:.2f}%")

# Step 6: Survival by gender
sns.countplot(x="sex", hue="survived", data=df, palette="Set2")
plt.title("Survival by Gender")
plt.show()

# Step 7: Survival by class
sns.countplot(x="class", hue="survived", data=df, palette="Set1")
plt.title("Survival by Passenger Class")
plt.show()

# Step 8: Age distribution
sns.histplot(df["age"].dropna(), bins=30, kde=True, color="skyblue")
plt.title("Age Distribution of Passengers")
plt.show()

# Step 9: Insights
print("\nInsights:")
print("- Women had higher survival rates than men.")
print("- First-class passengers survived more often than third-class passengers.")
print("- Younger passengers (children) had higher survival chances.")



